export const PROJECTS = [
  {
    name: 'Minesweeper',
    description: 'I decided to put a modern twist on a classic game and reconstruct Minesweeper with React and Redux.',
    technologies: 'React, Redux, Webpack, Immutable, ES6, Babel, React-Bootstrap, Sass',
    link: 'http://glasser88.github.io/Earthquake-Map/#/',
    screenshotOne: 'appImage',
    screenshotTwo: 'bigImage',
    year: 2016,
    company: 'Personal Project',
    mainTechnology: 'React Redux',
  },
  {
    name: 'Blackjack',
    description: 'For a game with endless possibilities and complex card combinations I will seemily always be working on new features.',
    technologies: 'React, Redux, Webpack, Immutable, ES6, Babel, React-Bootstrap, Sass',
    link: 'http://glasser88.github.io/Earthquake-Map/#/',
    screenshotOne: 'appImage',
    screenshotTwo: 'bigImage',
    year: 2016,
    company: 'Personal Project',
    mainTechnology: 'React Redux',
  },
  {
    name: 'Earthquake Tracker',
    description: 'For my first ever Angular.js project I combined the power of Google Maps and an Earthquake API to create the ultimate tracker.',
    technologies: 'Angular, Google Maps, CSS3, HTML5',
    link: 'http://glasser88.github.io/Earthquake-Map/#/',
    screenshotOne: 'appImage',
    screenshotTwo: 'bigImage',
    year: 2015,
    company: 'Personal Project',
    mainTechnology: 'Angular',
  },
  {
    name: 'Small Game Hunter',
    description: 'One of my first ever projects as a developer still remains one of my favorite. A new spin on the Duck Hunting classic.',
    technologies: 'J-Query, CSS3, HTML5',
    link: 'http://glasser88.github.io/Earthquake-Map/#/',
    screenshotOne: 'appImage',
    screenshotTwo: 'bigImage',
    year: 2015,
    company: 'Personal Project',
    mainTechnology: 'J-Query',
  }
];
